EXPORT Layout_CESurveys :=RECORD
  UNSIGNED3 SHOW_KEY;
  UNICODE7 TSSBOOTHID;
  UNSIGNED1 QUESTION_NBR;
  UNICODE QUESTION_TEXT;
  UNICODE19 CREATED_DT;
  UNSIGNED5 SURVEY_NBR;
  UNICODE45 ANSWER_TEXT;
  UNICODE19 CONTACT_NAME;
  UNICODE1 WANT_TO_BE_CONTACTED;
  INTEGER6 CONTACT_PHONE;
  UNSIGNED1 COUNTRY_CODE;
  UNICODE COMMENTS;


END;