EXPORT layout_ceIssueItem := record
  UNSIGNED3 SHOW_KEY;
  UNSIGNED5 ISSUE_KEY;
  UNSIGNED5 KEY;
  UNICODE19 CREATED_DT;
  UNICODE33 CREATED_BY;
  UNICODE19 UPDATED_DT;
  UNICODE33 UPDATED_BY;
  UNICODE8 SOURCE;
  UNSIGNED1 STATUS;
  UNSIGNED3 CONTRACTOR_KEY;
  UNSIGNED3 SHOW_CONTRACTOR_ASSN_KEY;
  UNICODE ISSUE_TEXT;
  UNSIGNED5 CE_SHOW_KEY;
  UNICODE1 EXHIBITOR_PRESENT_IND;
  UNICODE9 TSSBOOTHID;

end;