OPTIONS:-gh
MODULE:Exhibition_ShowExtractOrderDetail
FILENAME:ShowExtractOrderDetail
FIELD:OrderNumber:TYPE(UNICODE):0,0
FIELD:OrderLineNumber:TYPE(UNICODE):0,0
FIELD:RevenueType:TYPE(UNICODE):0,0
FIELD:RevenueItem:TYPE(UNICODE):0,0
FIELD:OrderLineStatus:TYPE(UNICODE):0,0
FIELD:QuantityOrdered:TYPE(UNICODE):0,0
FIELD:TotalPrice:TYPE(UNICODE):0,0
