EXPORT Layout_MYSShowFeatures := RECORD
  UNICODE Event;
	UNICODE Edition;
	UNICODE EXHIBITOR;
	UNICODE EMAIL;
	UNICODE EXHIBITORID;
	UNICODE PASSWORD;	
	UNICODE FEATURE_TITLE;
	UNICODE MEDIA_FILE;
	END;
