EXPORT Layout_ReedSubgroupData := RECORD
  UNICODE10 SHOW_KEY;
  UNSIGNED1 GROUP_ID;
  UNSIGNED1 SUBGROUP_ID;
  UNICODE50 DESCRIPTION;
  UNICODE7 USER_ID;
  UNICODE19 LAST_UPDATE_DT;
  UNSIGNED1 PM_TYPE;
  REAL4 DISCOUNT_PCT;
END;
