
OPTIONS:-gh
MODULE:Exhibition_InvoiceInfo
FILENAME:InvoiceInfo
FIELD:CustomerID:TYPE(UNICODE):0,0
FIELD:Event:TYPE(UNICODE):0,0
FIELD:Edition:TYPE(UNICODE):0,0
FIELD:Invoiced:TYPE(UNICODE):0,0
FIELD:Paid:TYPE(UNICODE):0,0


