EXPORT Layout_MYSProducts := RECORD
  UNICODE5 Event;
  UNSIGNED2 Edition;
  UNSIGNED4 PROD_ID;
  UNICODE43 PARENT_PRODUCT;
  UNICODE45 PRODUCT;
  UNSIGNED3 EXHIBITORID;
  UNICODE64 EXHIBITOR;
  UNICODE10 BOOTH;

END;