OPTIONS:-gh
MODULE:Exhibition_ReedGroupData
FILENAME:ReedGroupData
FIELD:SHOW_KEY:TYPE(UNICODE):0,0
FIELD:GROUP_ID:TYPE(UNICODE):0,0
FIELD:DESCRIPTION:TYPE(UNICODE):0,0
FIELD:PRINT_ON_INV_IND:TYPE(UNICODE):0,0
FIELD:GL_ACCT_NBR:TYPE(UNICODE):0,0
FIELD:GL_SUB_NBR:TYPE(UNICODE):0,0
FIELD:USER_ID:TYPE(UNICODE):0,0
FIELD:LAST_UPDATE_DT:TYPE(UNICODE):0,0
FIELD:INV_ST_SUM_GROUP:TYPE(UNICODE):0,0
FIELD:PM_TYPE:TYPE(UNICODE):0,0
FIELD:DISCOUNT_PCT:TYPE(UNICODE):0,0

