EXPORT Layout_ReedGroupData := RECORD
  UNICODE10 SHOW_KEY;
  UNSIGNED1 GROUP_ID;
  UNICODE46 DESCRIPTION;
  UNICODE1 PRINT_ON_INV_IND;
  UNICODE6 GL_ACCT_NBR;
  UNICODE5 GL_SUB_NBR;
  UNICODE6 USER_ID;
  UNICODE19 LAST_UPDATE_DT;
  UNSIGNED1 INV_ST_SUM_GROUP;
  UNSIGNED1 PM_TYPE;
  REAL4 DISCOUNT_PCT;


END;